"""Versioned API schema migrations (SQLite now, Postgres-ready SQL later).

This process does **not** open a hosted Postgres instance. ``Store`` stays on
local SQLite. ``dump_sql("postgres")`` prints the same revisions for a future
self-hosted ``psql`` apply — never a paid Render database from this package.
"""

from __future__ import annotations

import argparse
import sqlite3
import time
from dataclasses import dataclass
from typing import Iterable

SCHEMA_MIGRATIONS_TABLE = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
);
"""

SQLITE_001 = """
CREATE TABLE IF NOT EXISTS api_keys (
    id INTEGER PRIMARY KEY,
    key_hash TEXT UNIQUE NOT NULL,
    key_prefix TEXT NOT NULL,
    name TEXT NOT NULL,
    tier TEXT NOT NULL CHECK (tier IN ('free', 'paid')),
    created_at TEXT NOT NULL,
    revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS usage_events (
    id INTEGER PRIMARY KEY,
    key_id INTEGER NOT NULL REFERENCES api_keys(id),
    ts REAL NOT NULL,
    path TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_usage_key_ts ON usage_events(key_id, ts);

CREATE TABLE IF NOT EXISTS score_history (
    id INTEGER PRIMARY KEY,
    ticker TEXT NOT NULL,
    scored_at REAL NOT NULL,
    score REAL NOT NULL,
    band TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    payload_hash TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_history_ticker ON score_history(ticker, scored_at);

CREATE TABLE IF NOT EXISTS watchlist_items (
    id INTEGER PRIMARY KEY,
    key_id INTEGER NOT NULL REFERENCES api_keys(id),
    ticker TEXT NOT NULL,
    UNIQUE(key_id, ticker)
);

CREATE TABLE IF NOT EXISTS webhooks (
    id INTEGER PRIMARY KEY,
    key_id INTEGER NOT NULL REFERENCES api_keys(id),
    url TEXT NOT NULL,
    secret TEXT NOT NULL,
    ticker TEXT,
    trigger TEXT NOT NULL DEFAULT 'band_cross',
    created_at TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS last_bands (
    key_id INTEGER NOT NULL REFERENCES api_keys(id),
    ticker TEXT NOT NULL,
    band TEXT NOT NULL,
    score REAL NOT NULL,
    updated_at REAL NOT NULL,
    PRIMARY KEY (key_id, ticker)
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id INTEGER PRIMARY KEY,
    webhook_id INTEGER NOT NULL REFERENCES webhooks(id),
    ticker TEXT NOT NULL,
    event TEXT NOT NULL,
    status_code INTEGER,
    delivered_at REAL NOT NULL,
    ok INTEGER NOT NULL
);
"""

POSTGRES_001 = """
CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash TEXT UNIQUE NOT NULL,
    key_prefix TEXT NOT NULL,
    name TEXT NOT NULL,
    tier TEXT NOT NULL CHECK (tier IN ('free', 'paid')),
    created_at TEXT NOT NULL,
    revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id BIGINT NOT NULL REFERENCES api_keys(id),
    ts DOUBLE PRECISION NOT NULL,
    path TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_usage_key_ts ON usage_events(key_id, ts);

CREATE TABLE IF NOT EXISTS score_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    scored_at DOUBLE PRECISION NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    band TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    payload_hash TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_history_ticker ON score_history(ticker, scored_at);

CREATE TABLE IF NOT EXISTS watchlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id BIGINT NOT NULL REFERENCES api_keys(id),
    ticker TEXT NOT NULL,
    UNIQUE(key_id, ticker)
);

CREATE TABLE IF NOT EXISTS webhooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id BIGINT NOT NULL REFERENCES api_keys(id),
    url TEXT NOT NULL,
    secret TEXT NOT NULL,
    ticker TEXT,
    trigger TEXT NOT NULL DEFAULT 'band_cross',
    created_at TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS last_bands (
    key_id BIGINT NOT NULL REFERENCES api_keys(id),
    ticker TEXT NOT NULL,
    band TEXT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (key_id, ticker)
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id BIGINT NOT NULL REFERENCES webhooks(id),
    ticker TEXT NOT NULL,
    event TEXT NOT NULL,
    status_code INTEGER,
    delivered_at DOUBLE PRECISION NOT NULL,
    ok INTEGER NOT NULL
);
"""

SQLITE_002 = """
CREATE INDEX IF NOT EXISTS idx_history_key_ticker
    ON score_history(key_id, ticker, scored_at);
"""

POSTGRES_002 = """
ALTER TABLE score_history ADD COLUMN IF NOT EXISTS key_id BIGINT REFERENCES api_keys(id);
CREATE INDEX IF NOT EXISTS idx_history_key_ticker
    ON score_history(key_id, ticker, scored_at);
"""


@dataclass(frozen=True)
class Migration:
    version: str
    sqlite: str
    postgres: str


MIGRATIONS: tuple[Migration, ...] = (
    Migration("001_initial", SQLITE_001, POSTGRES_001),
    Migration("002_history_tenant", SQLITE_002, POSTGRES_002),
)


def _iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _table_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    names: set[str] = set()
    for row in rows:
        try:
            names.add(str(row["name"]))
        except (KeyError, IndexError, TypeError):
            names.add(str(row[1]))
    return names


def applied_versions(conn: sqlite3.Connection) -> list[str]:
    conn.executescript(SCHEMA_MIGRATIONS_TABLE)
    rows = conn.execute(
        "SELECT version FROM schema_migrations ORDER BY version"
    ).fetchall()
    out: list[str] = []
    for row in rows:
        try:
            out.append(str(row["version"]))
        except (KeyError, IndexError, TypeError):
            out.append(str(row[0]))
    return out


def apply_sqlite_migrations(conn: sqlite3.Connection) -> list[str]:
    """Apply pending revisions. Safe on a fresh or already-initialized SQLite file."""
    applied = set(applied_versions(conn))
    ran: list[str] = []
    for migration in MIGRATIONS:
        if migration.version in applied:
            continue
        if migration.version == "002_history_tenant":
            cols = _table_columns(conn, "score_history")
            if "key_id" not in cols:
                conn.execute(
                    "ALTER TABLE score_history ADD COLUMN key_id INTEGER "
                    "REFERENCES api_keys(id)"
                )
            conn.executescript(migration.sqlite)
        else:
            conn.executescript(migration.sqlite)
        conn.execute(
            "INSERT INTO schema_migrations (version, applied_at) VALUES (?, ?)",
            (migration.version, _iso()),
        )
        ran.append(migration.version)
    return ran


def dump_sql(dialect: str = "sqlite") -> str:
    """Full SQL for a dialect. Postgres is for a future self-hosted apply."""
    key = (dialect or "sqlite").strip().lower()
    if key not in {"sqlite", "postgres", "postgresql"}:
        raise ValueError(f"unknown dialect: {dialect}")
    chunks = [SCHEMA_MIGRATIONS_TABLE.strip(), ""]
    for migration in MIGRATIONS:
        body = migration.sqlite if key == "sqlite" else migration.postgres
        chunks.append(f"-- {migration.version}")
        chunks.append(body.strip())
        chunks.append("")
    return "\n".join(chunks).strip() + "\n"


def iter_versions() -> Iterable[str]:
    return tuple(m.version for m in MIGRATIONS)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Dump RAT API schema migrations (SQLite default; Postgres SQL only)."
    )
    parser.add_argument(
        "--dialect",
        choices=("sqlite", "postgres"),
        default="sqlite",
        help="SQL dialect to print. postgres is not executed here.",
    )
    args = parser.parse_args(argv)
    print(dump_sql(args.dialect), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
