"""Local SQLite migrations + Postgres-ready SQL dump (no hosted DB)."""

from __future__ import annotations

import sqlite3
from pathlib import Path

from rwa_score.api.migrations import (
    MIGRATIONS,
    apply_sqlite_migrations,
    dump_sql,
    iter_versions,
)
from rwa_score.api.settings import ApiSettings
from rwa_score.api.store import SCHEMA, Store


def test_fresh_sqlite_applies_all_revisions(tmp_path: Path) -> None:
    db = tmp_path / "fresh.sqlite"
    store = Store(db)
    versions = {
        row["version"]
        for row in store._conn.execute("SELECT version FROM schema_migrations")
    }
    assert versions == set(iter_versions())
    cols = {row["name"] for row in store._conn.execute("PRAGMA table_info(score_history)")}
    assert "key_id" in cols
    assert "payload_hash" in cols
    store.close()


def test_legacy_sqlite_gains_key_id(tmp_path: Path) -> None:
    db = tmp_path / "legacy.sqlite"
    conn = sqlite3.connect(db)
    conn.executescript(
        """
        CREATE TABLE score_history (
            id INTEGER PRIMARY KEY,
            ticker TEXT NOT NULL,
            scored_at REAL NOT NULL,
            score REAL NOT NULL,
            band TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            payload_hash TEXT NOT NULL
        );
        INSERT INTO score_history
            (ticker, scored_at, score, band, payload_json, payload_hash)
            VALUES ('NVDA', 1.0, 80.0, 'GREEN', '{}', 'abc');
        """
    )
    conn.commit()
    conn.close()

    store = Store(db)
    cols = {row["name"] for row in store._conn.execute("PRAGMA table_info(score_history)")}
    assert "key_id" in cols
    row = store._conn.execute("SELECT key_id FROM score_history WHERE ticker = 'NVDA'").fetchone()
    assert row["key_id"] is None
    store.close()


def test_history_is_tenant_scoped(tmp_path: Path) -> None:
    store = Store(tmp_path / "hist.sqlite")
    raw_a = store.create_key(name="a", tier="paid")
    raw_b = store.create_key(name="b", tier="paid")
    a = store.lookup_key(raw_a)
    b = store.lookup_key(raw_b)
    assert a is not None and b is not None
    store.record_history(
        ticker="NVDA",
        score=80.0,
        band="GREEN",
        payload_json="{}",
        payload_hash="aaa",
        key_id=a.id,
    )
    store.record_history(
        ticker="NVDA",
        score=20.0,
        band="RED",
        payload_json="{}",
        payload_hash="bbb",
        key_id=b.id,
    )
    only_a = store.get_history("NVDA", key_id=a.id)
    only_b = store.get_history("NVDA", key_id=b.id)
    assert [row["payload_hash"] for row in only_a] == ["aaa"]
    assert [row["payload_hash"] for row in only_b] == ["bbb"]
    assert only_a[0]["key_id"] == a.id
    store.close()


def test_postgres_dump_is_dialect_ready_and_not_executed() -> None:
    sql = dump_sql("postgres")
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "ADD COLUMN IF NOT EXISTS key_id" in sql
    assert "score_history" in sql
    assert "INTEGER PRIMARY KEY" not in sql
    sqlite_sql = dump_sql("sqlite")
    assert SCHEMA in sqlite_sql or "CREATE TABLE IF NOT EXISTS score_history" in sqlite_sql
    assert {m.version for m in MIGRATIONS} == {"001_initial", "002_history_tenant"}


def test_settings_records_postgres_url_but_store_stays_sqlite(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.setenv("RWA_API_DATABASE_URL", "postgresql://example.invalid/rat")
    monkeypatch.setenv("RWA_API_DB_PATH", str(tmp_path / "still.sqlite"))
    settings = ApiSettings.from_env()
    assert settings.db_backend == "postgres"
    assert settings.database_url.startswith("postgresql://")
    store = Store(settings.db_path)
    store.create_key(name="local", tier="free")
    assert settings.db_path.exists()
    store.close()


def test_apply_is_idempotent(tmp_path: Path) -> None:
    conn = sqlite3.connect(tmp_path / "once.sqlite")
    conn.row_factory = sqlite3.Row
    first = apply_sqlite_migrations(conn)
    second = apply_sqlite_migrations(conn)
    conn.commit()
    assert first == ["001_initial", "002_history_tenant"]
    assert second == []
    conn.close()
