"""Plain-language score explanations via xAI (Grok), with a safe fallback.

Uses ``requests`` only. Missing ``XAI_API_KEY`` or any HTTP/parse failure
returns a templated summary from pillar notes — never raises to the UI.
"""

from __future__ import annotations

import os
from typing import Any

import requests

XAI_CHAT_URL = "https://api.x.ai/v1/chat/completions"
XAI_MODEL = "grok-4.1-fast"
XAI_MAX_TOKENS = 300
XAI_TIMEOUT = 20

SYSTEM_PROMPT = (
    "You explain RWA transparency scores for a hackathon demo. "
    "Be concise (under 220 words). Use only the provided score, band, "
    "pillar notes, evidence, and issuer note. Do not give financial advice "
    "or recommend buying or selling. If the issuer note says the token is "
    "a debt wrapper, say that clearly."
)

AI_FOOTNOTE = "generated by AI, not financial advice"


def build_explain_prompt(result: dict[str, Any]) -> str:
    """Build the user prompt from a score payload."""
    ticker = result.get("ticker") or "unknown"
    issuer = result.get("issuer") or "unknown"
    score = result.get("score")
    band = result.get("band") or result.get("band_label") or "?"
    note = result.get("issuer_note") or "No issuer-specific equity-vs-debt note."
    explanations = result.get("explanations") or {}
    verification = result.get("verification") or {}
    subscores = result.get("subscores") or {}
    flags = result.get("flags") or []
    notes = result.get("notes") or []

    lines = [
        f"Ticker: {ticker}",
        f"Issuer: {issuer}",
        f"Score: {score}",
        f"Band: {band}",
        f"Issuer note: {note}",
        "Pillars:",
    ]
    for pillar in ("backing", "reserves", "redemption", "price", "disclosure"):
        why = explanations.get(pillar) or ""
        block = verification.get(pillar) or {}
        evidence = block.get("evidence") or ""
        level = block.get("level") or ""
        sub = subscores.get(pillar, "")
        lines.append(
            f"- {pillar}: score={sub}; level={level}; "
            f"evidence={evidence}; notes={why}"
        )
    if flags:
        lines.append("Risk flags: " + "; ".join(str(f) for f in flags))
    if notes:
        lines.append("Score notes: " + "; ".join(str(n) for n in notes))
    lines.append(
        "Write a short plain-language explanation of why this score landed "
        "where it did. Not financial advice."
    )
    return "\n".join(lines)


def fallback_explanation(result: dict[str, Any]) -> str:
    """Templated summary from pillar notes when xAI is unavailable."""
    ticker = result.get("ticker") or "This token"
    score = result.get("score")
    band = result.get("band") or "?"
    note = result.get("issuer_note") or "No issuer-specific equity-vs-debt note."
    explanations = result.get("explanations") or {}
    verification = result.get("verification") or {}
    parts = [
        f"{ticker} scores {score} ({band}).",
        note,
    ]
    for pillar in ("backing", "reserves", "redemption", "price", "disclosure"):
        block = verification.get(pillar) or {}
        evidence = block.get("evidence") or ""
        why = explanations.get(pillar) or ""
        snippet = evidence or why
        if snippet:
            parts.append(f"{pillar.capitalize()}: {snippet}")
    parts.append("This is an automated summary, not financial advice.")
    return " ".join(parts)


def explain_score(
    result: dict[str, Any],
    *,
    session: requests.Session | None = None,
    api_key: str | None = None,
) -> str:
    """Return a short explanation. Never raises; falls back on any failure."""
    payload = result or {}
    key = os.environ.get("XAI_API_KEY") if api_key is None else api_key
    if not key:
        return fallback_explanation(payload)

    prompt = build_explain_prompt(payload)
    try:
        sess = session or requests.Session()
        resp = sess.post(
            XAI_CHAT_URL,
            headers={
                "Authorization": f"Bearer {key}",
                "Content-Type": "application/json",
            },
            json={
                "model": XAI_MODEL,
                "max_tokens": XAI_MAX_TOKENS,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
            },
            timeout=XAI_TIMEOUT,
        )
        if getattr(resp, "status_code", 0) != 200:
            return fallback_explanation(payload)
        body = resp.json()
        text = (
            ((body.get("choices") or [{}])[0].get("message") or {}).get("content") or ""
        ).strip()
        return text or fallback_explanation(payload)
    except Exception:  # noqa: BLE001 — UI must never crash on explainer
        return fallback_explanation(payload)
