"""Plain-language score explanations via xAI (Grok), with a safe fallback.

Uses ``requests`` only. Missing ``XAI_API_KEY`` or any HTTP/parse failure
returns a templated summary from pillar notes — never raises to the UI.
"""

from __future__ import annotations

import os
import re
from typing import Any

import requests

from .scorer import WEIGHTS

XAI_CHAT_URL = "https://api.x.ai/v1/chat/completions"
# Official Grok 4.1 Fast slug (hyphens). ``grok-4.1-fast`` is not a valid
# xAI model id and 400s, which the UI used to report as a timeout/skip.
# After 2026-05-15 this alias serves grok-4.3; override with XAI_MODEL.
DEFAULT_XAI_MODEL = "grok-4-1-fast"
XAI_MODEL = DEFAULT_XAI_MODEL
XAI_MAX_TOKENS = 300
XAI_CONNECT_TIMEOUT = 5.0
XAI_TIMEOUT = 30
XAI_USER_AGENT = "rwa-transparency-score/0.3 (+hackathon demo)"
_SECRET_RE = re.compile(
    r"(?i)(Bearer\s+)\S+|(?:xai-|sk-)[A-Za-z0-9_-]{8,}"
)

SYSTEM_PROMPT = (
    "You explain RWA transparency scores for a hackathon demo. "
    "Be concise (under 220 words). Use only the provided score, band, "
    "pillar notes, evidence, and issuer note. Do not give financial advice "
    "or recommend buying or selling. If the issuer note says the token is "
    "a debt wrapper, say that clearly."
)

AI_FOOTNOTE = "generated by AI, not financial advice"


def resolve_xai_model() -> str:
    """Return ``XAI_MODEL`` env override or the official default slug."""
    override = (os.environ.get("XAI_MODEL") or "").strip()
    return override or DEFAULT_XAI_MODEL


def xai_headers(api_key: str) -> dict[str, str]:
    """Auth + browser-like Accept/UA. Never log the returned Authorization."""
    return {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "User-Agent": XAI_USER_AGENT,
    }


def xai_timeout(read_seconds: float) -> tuple[float, float]:
    """``(connect, read)`` so a hung TCP connect fails fast."""
    read = max(XAI_CONNECT_TIMEOUT, float(read_seconds))
    return (XAI_CONNECT_TIMEOUT, read)


def redact_xai_error(text: str, *, limit: int = 160) -> str:
    """Public-safe snippet of an xAI / HTTP error. Never includes the key."""
    cleaned = _SECRET_RE.sub(
        lambda match: (match.group(1) + "[redacted]") if match.group(1) else "[redacted]",
        str(text or ""),
    )
    cleaned = " ".join(cleaned.split())
    return cleaned[:limit] if cleaned else "unknown error"


def log_xai_failure(reason: str) -> None:
    """Render-visible line without secrets. Matches the X_SHARE_FAIL style."""
    print(f"XAI_FAIL detail={redact_xai_error(reason, limit=220)}", flush=True)


def build_explain_prompt(result: dict[str, Any]) -> str:
    """Build the user prompt from a score payload."""
    ticker = result.get("ticker") or "unknown"
    issuer = result.get("issuer") or "unknown"
    score = result.get("score")
    band = result.get("band") or result.get("band_label") or "?"
    note = result.get("issuer_note") or "No issuer-specific equity-vs-debt note."
    explanations = result.get("explanations") or {}
    verification = result.get("verification") or {}
    subscores = result.get("subscores") or {}
    flags = result.get("flags") or []
    notes = result.get("notes") or []

    lines = [
        f"Ticker: {ticker}",
        f"Issuer: {issuer}",
        f"Score: {score}",
        f"Band: {band}",
        f"Issuer note: {note}",
        "Pillars:",
    ]
    for pillar in WEIGHTS:
        why = explanations.get(pillar) or ""
        block = verification.get(pillar) or {}
        evidence = block.get("evidence") or ""
        level = block.get("level") or ""
        sub = subscores.get(pillar, "")
        lines.append(
            f"- {pillar}: score={sub}; level={level}; "
            f"evidence={evidence}; notes={why}"
        )
    if flags:
        lines.append("Risk flags: " + "; ".join(str(f) for f in flags))
    if notes:
        lines.append("Score notes: " + "; ".join(str(n) for n in notes))
    lines.append(
        "Write a short plain-language explanation of why this score landed "
        "where it did. Not financial advice."
    )
    return "\n".join(lines)


def fallback_explanation(result: dict[str, Any]) -> str:
    """Templated summary from pillar notes when xAI is unavailable."""
    ticker = result.get("ticker") or "This token"
    score = result.get("score")
    band = result.get("band") or "?"
    note = result.get("issuer_note") or "No issuer-specific equity-vs-debt note."
    explanations = result.get("explanations") or {}
    verification = result.get("verification") or {}
    parts = [
        f"{ticker} scores {score} ({band}).",
        note,
    ]
    for pillar in WEIGHTS:
        block = verification.get(pillar) or {}
        evidence = block.get("evidence") or ""
        why = explanations.get(pillar) or ""
        snippet = evidence or why
        if snippet:
            parts.append(f"{pillar.capitalize()}: {snippet}")
    parts.append("This is an automated summary, not financial advice.")
    return " ".join(parts)


def explain_score(
    result: dict[str, Any],
    *,
    session: requests.Session | None = None,
    api_key: str | None = None,
) -> str:
    """Return a short explanation. Never raises; falls back on any failure."""
    payload = result or {}
    key = os.environ.get("XAI_API_KEY") if api_key is None else api_key
    if not key:
        return fallback_explanation(payload)

    prompt = build_explain_prompt(payload)
    try:
        sess = session or requests.Session()
        resp = sess.post(
            XAI_CHAT_URL,
            headers=xai_headers(key),
            json={
                "model": resolve_xai_model(),
                "max_tokens": XAI_MAX_TOKENS,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
            },
            timeout=xai_timeout(XAI_TIMEOUT),
        )
        status = getattr(resp, "status_code", 0)
        if status != 200:
            body_text = ""
            try:
                body_text = resp.text or ""
            except Exception:  # noqa: BLE001
                body_text = ""
            log_xai_failure(f"HTTP {status} {body_text}")
            return fallback_explanation(payload)
        body = resp.json()
        text = (
            ((body.get("choices") or [{}])[0].get("message") or {}).get("content") or ""
        ).strip()
        if not text:
            log_xai_failure("empty model reply")
            return fallback_explanation(payload)
        return text
    except Exception as exc:  # noqa: BLE001 — UI must never crash on explainer
        log_xai_failure(str(exc))
        return fallback_explanation(payload)
